{% set name = "sos-bash" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3a2c6ded5732ef5e321874a112337ddbdba136a4a26fae90500955960fb0f8d8

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - sos-notebook >=0.19.4
    - calysto_bash
    - python >=3.6

test:
  requires:
    - nose
    - pytest
    - selenium
  imports:
    - sos_bash

about:
  home: https://github.com/vatlab/sos-bash
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: SoS language module for bash
  doc_url: https://vatlab.github.io/sos-docs/
  dev_url: https://github.com/vatlab/sos-bash

extra:
  recipe-maintainers:
    - BoPeng
