travis:
  secure:
    BINSTAR_TOKEN: O4GwYy/hXT4vtn8f4ZexLZ++slT3OIIBaZFl9dPjSc7bwxN/trKxKhviqBYJ1Eo/mSwu+4aqUs3ligvHlK1+x6dI0Ji9bg9r/FowVC2DLtL31V5E5RaQ8AZaPtsL+r9a5dDzNX8Il/ofuCa4I17HF5IrPxEVdmghOe6+FNJkjmu1Zj4nWAkGmQu07Q1f91QXmqs95UFf7vvQA69T/0FKpgGbplZbvEgi1N6S+Dhz+bAfVCsEKtW1x//YmohXNDnhngT6jNeqVvDuCPXSrucqKekJCucw1i+3y5lnbUd4WahUF0i6gy1Z583pRfzKvpByprV7hlj25Hfd6b7c/qmMSNZwFmJMPiOPZ25SLfne55Y1cMcM6oFOJg/5Tfhd0FG5H3ntF+xpiU4rMrzJUaJRG8ri1Cj0rf/JeEV30jeSnkFGj4r9MWbLsG3UVgDYK18zD8NtpQiqctESFO4e9nbWjkTUJk2cXhw3qzMBovOBQchaMhij010JPc8QEz2lxPBPd4EGDaSPCNl2QVQsSz7q+8oAU5PYwfF0e6KB7sGl4MDbL7+du9j2nCfUh54ZzYr9j8sjbMuWebcEaPLxtrTZzYqsosvAqy9gUaw9JB1Q3m924Il6l2Cc/8cgl9wa+aezlF0CRLxLKFoo5h+jxBn3KyNJZZnqJTeNiKUqCj+pRsg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
